kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: app
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: app
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: 535002850032.dkr.ecr.us-east-1.amazonaws.com/expense-frontend:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: frontend